### ISSUE TITLE
Sea Level Rise Report - numbers not intuitive

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#10]
The numbers displayed for each increasing scenario are not cumulative, but rather show the additional acreage lost versus the previous scenario - it would be less confusing if they were additive.

**Comment by tchaddad** [comment]
This is incorrect interpretation of what the scenarios are.

The scenarios are not additive, each stands alone. Each is inclusive of all change from the present day scenario under the specified amount of sea level rise. 

For example - the 1.5m scenario is measured against the present day scenario, and shows what sea levels would look like if we had 1.5m of sea level rise.

**Comment by mmosesOCMP** [comment]
We interpret the Lost Intertidal Habitat (in Acres) column actually reflects remaining acres of intertidal habitat in the unclipped polygon, subtracted from the Present Day Intertidal Area. If so:

- New header = Sea level rise is predicted to cause the following changes in the intertidal habitat within this designated area:

- New column heading = Remaining Intertidal Habitat (in Acres)

- New footer = *due to the fact that future intertidal areas may be above present-day MHW, this analysis is based on intertidal area contained in the unclipped site polygon

**Comment by danyocum** [comment]
Updated SLR report looks like:
![image](https://user-images.githubusercontent.com/4041378/85600274-2a0e6e00-b602-11ea-9d32-f5bb5e78086f.png)

**Comment by mmosesOCMP** [comment]
looks good
