### ISSUE TITLE
Sea Level Rise Risk Report - needs explainer

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#11]
It is not clear what is meant by these - it would be good to include a brief explainer below like we have for Important Bird Colonies.

**Comment by tchaddad** [comment]
See if the explanation I gave in https://github.com/orcoastalmgmt/orSeaSketch/issues/10 makes sense to you. We should come up with some sort of text that explains the confusion, and then if you want it to appear in the report we will have to assign to the SeaSketch folks.

**Comment by mmosesOCMP** [comment]
We interpret the Lost Intertidal Habitat (in Acres) column actually reflects remaining acres of intertidal habitat in the unclipped polygon, subtracted from the Present Day Intertidal Area. If so:

- New header = Sea level rise is predicted to cause the following changes in the intertidal habitat within this designated area:

- New column heading = Remaining Intertidal Habitat (in Acres)

- New footer = *due to the fact that future intertidal areas may be above present-day MHW, this analysis is based on intertidal area contained in the unclipped site polygon

**Comment by tchaddad** [comment]
Scratch the above comment.

What is needed is an explanation in the footer of the report of how Risk levels were assigned:

![image](https://user-images.githubusercontent.com/1042618/85463049-0b08d100-b55b-11ea-8635-6f67b472e2ef.png)

**Comment by danyocum** [comment]
I've added an explanation below the sea level rise risk report:
![image](https://user-images.githubusercontent.com/4041378/85600113-064b2800-b602-11ea-93c4-0f72351418e8.png)

**Comment by mmosesOCMP** [comment]
looks good
