### ISSUE TITLE
Key Species Present Report

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#13]
species names are not formated properly; what the 'Count' indicates is also not explained

**Comment by danyocum** [comment]
For now, I'm assuming they're all the scientific name, so its first letter capitalized, everything else lower, everything italicized

**Comment by danyocum** [comment]
The count is the number of key species sites that the sketch/collection overlaps with (and have that species). I've changed the column header to 'Number of Sites' -- let me know if that is sufficient.

**Comment by mmosesOCMP** [comment]
@danyocum I think I would lean toward removing the column as I think our potential for this to be misleading or non-intuitive is much higher than it's likelihood to be informative or critical. @tchaddad Any alternative suggestions on this one?

**Comment by tchaddad** [comment]
Yeah if we were advertising this layer differently (say, as long term research station locations), then number of sites would make sense to show, but I'm fine with removing it in this context.

**Comment by danyocum** [comment]
Agreed: when in doubt, make the reports simpler. Count removed
