### ISSUE TITLE
Long Term Research Species Found Report

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#14]
species names are not formatted properly; what the 'Count' indicates is also not explained

**Comment by tchaddad** [comment]
Check Cape Arago area and look for PISCO data.

Count is not intuitive to lay people. Need to confirm if table is P/A, or if it truly contains count. Also might need to confirm with PISCO

**Comment by mmosesOCMP** [comment]
Clarification on species names: 

- Scientific names are always italicized, as is the abbreviation "_spp_", for species.
- Genus, Family, and higher taxonomic classifications are always capitalized, species and subspecies are lowercase. 
- Common English names generally follow the convention of capitalizing the first word, but not the subsequent words (if any). This is particularly true for birds, in which the common English names are standardized by the American Ornithological Society and adhered to by many other scientific organizations, including non-avian related groups.

Examples: 

Incorrect: corallina spp, mytilus californianus, cnidaria, Black Oystercatcher, Double-Crested Cormorant

Correct: _Corallina spp._, _Mytilus californianus_, Cnidaria, Black oystercatcher, Double-crested cormorant

Updating these may just be a matter of updating the source datasets ultimately, but if there is a way to autocorrect the names as they appear in the reports that would be nice.

**Comment by danyocum** [comment]
I can fix this in the simple case, like in the bird species names, since they're all the same. I can't change the formatting on the fly without knowing which type of value is coming back -- are the key species and long term research species a mix of common, scientific, and genus/family/higher taxonomic classifications? If they are, I would need them to be split out into separate groups to be able to change the formatting.

**Comment by danyocum** [comment]
For now, I'm assuming they're all the scientific name, so its first letter capitalized, everything else lower, everything italicized

**Comment by danyocum** [comment]
I'm not sure what the 'count' is, looking at the data I can't really tell. Do you want me to just hide the count column and show the names? 

I think its just the number of the LTER transects, sites, etc. that it intersects with.

**Comment by mmosesOCMP** [comment]
@danyocum The key species and long term research species look to largely be limited to species and genera classification, so your suggestion above should suffice. Bird species present and marine mammal species present seem to have a mix.

For counts: if they are indeed LTER transects, etc then yes, we should remove that column. I think having any sort of count would only be relevant to our users if it was number of colonies/rookeries, or a literal count of individuals, which would be misleading due to sampling bias anyway. As long as the species listed represent what is present within the polygon they drew, rather than a much larger geographic area, then that should work.

**Comment by danyocum** [comment]
@mmosesOCMP I'm using the transects, polygons, stations, and points for the LTER species, but maybe I should just be using the point data? The points will be included in the polygon that the user draws, but with the transects and polygons, it might not be -- it could be anywhere within the shape. Should I change to points only and then update count to be 'Number of Sites'? Or Use points and get rid of count altogether?

**Comment by danyocum** [comment]
I've removed the count column for now, let me know if I should restrict the datasets to be just point data.

**Comment by mmosesOCMP** [comment]
looks good
