### ISSUE TITLE
NPDES Outfalls Report

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#16]
no idea what this is - explainer would be good

**Comment by tchaddad** [comment]
**NPDES = National Pollutant Discharge Elimination System**
(for more info see https://www.epa.gov/npdes)

"The NPDES permit program addresses water pollution by regulating point sources that discharge pollutants to waters of the United States."

This data set displays point locations where holders of NPDES permits are discharging wastewater.

**Comment by tchaddad** [comment]
I've added the above info to the layer description in the table of contents. Feel free to review, edit as you see fit, and close the issue if you are happy with this solution.

If you don't like where this information appears, it will have to be added to the report template by the SeaSketch folks.

**Comment by mmosesOCMP** [comment]
That works just fine. I didn't even realize that was an option to be honest, and probably preferable that it's something we can do rather than using SeaSketch hours for it.
