### ISSUE TITLE
Recreational Activities Report

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#17]
not sure what the Counts indicate here - another explainer would be good

**Comment by tchaddad** [comment]
These data are the panel point results from the 

- **Boating Recreational Ocean Users** Study. This group aggregated the following activities: sailing, power boating, personal water crafts, windsurfing, kite boarding, charter trips, and tow-in surfing - 
-  the **Human-powered group** in the Recreational Ocean Users Study. This group aggregated the following activities: Kayaking, Surfing, Swimming, Scuba diving, Snorkeling and Skimboarding.
- the **Shore group** of the Recreational Ocean Users Study. This group aggregated the following activities: beach going, hang-gliding, scenic enjoyment, storm watching, biking/hiking, off-road vehicles, and photography. 
- additional **Shore group** of the Recreational Ocean Users Study. This group aggregated the following activities: bird watching, tide-pooling and whale watching. 

These data were collected to create a baseline of use patterns for Oregon's recreational non-consumptive ocean users. These data include only the last trip data collected over the summer of 2010. These data were collected as part of Oregon's Territorial Sea Plan revision.

**Comment by mmosesOCMP** [comment]
Add the above explanation (or maybe slightly briefer one) to the report.

**Comment by danyocum** [comment]
I've added the text above to the bottom of the report.
