### ISSUE TITLE
Human Uses Attributes & Reports - very slow to calculate

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#18]
This subtab takes way longer to analyze than the others - it seems to be the NonFishHarvest calculation which also times/errors out frequently. Any way to fix this?

**Comment by tchaddad** [comment]
@mmosesOCMP are these layers still in the tool, or did we decide in other issues that we would remove them? 

If so, then this speed problem may go away when the SeaSketch team removes those layers from the report

**Comment by mmosesOCMP** [comment]
@tchaddad Yes, we did remove those datalayers.

**Comment by danyocum** [comment]
removed the reports

**Comment by mmosesOCMP** [comment]
@danyocum I thought perhaps this was resolved, but it appears the Human Use reports are still getting hung up on the analysis and it's not clear why.

**Comment by danyocum** [comment]
@mmosesOCMP Can you share the sketches/collections you have that are getting hung up in the Staff Forum?

**Comment by danyocum** [comment]
oh, nevermind. I see it - I think I missed a file in my check in and its throwing an error. I should have it fixed shortly.

**Comment by danyocum** [comment]
@mmosesOCMP Fixed the bug, should complete correctly now.

**Comment by mmosesOCMP** [comment]
looks good
