### ISSUE TITLE
Commercial harvest data layers (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#19]
Commercial harvest of intertidal invertebrates:  the data are not spatially specific.  In many cases, the harvest is just a few animals, likely from only one or two sites.  The map shows the entire intertidal area of the state as the harvest area.  This depiction is unsuitable for a number of reasons:
-	Rocky intertidal organisms wouldn’t be in the sandy beach environment
-	Commercial harvest would not occur in the areas closed to harvest
-	Commercial harvest would not occur in inaccessible areas
-	Commercial harvest for the infrequently harvested animals would only be at one or two sites.
-	Commercial harvest for the more frequent animals would still be at a limited number of sites (we don’t know which sites)
The data do not support a spatial depiction of commercial harvest, and these layers should be removed from the tool.

**Comment by tchaddad** [comment]
I think Moses you have the power to remove these data from the tool, so if you agree with Dave, then feel free to go ahead and do it.

The data that came to us from ODFW was not very spatially specific, so I'd be happy to re-add if they eventually are able to provide more specificity.

**Comment by mmosesOCMP** [comment]
@DrewLanier What are your thoughts on removing these layers?

**Comment by mmosesOCMP** [comment]
I have deleted these layers.
