### ISSUE TITLE
Sport Intertidal Harvest of Abalone (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#21]
-	Showing the entire length of coastline north of Coquille as one large harvest area is deceptive, implying that abalone harvest occurs in all of the areas shown.
-	The data are for the cumulative harvest during the 10-year time period, not harvest per year.  This is not clear in the legend or the metadata.
-	The outer boundary of the subtidal harvest appears too deep. What depth contour was used?  It should be around 15 m.  
-	The fact that the current harvest is zero (it’s closed to harvest) should be indicated somewhere.

**Comment by tchaddad** [comment]
We will need to have the seaketch folks make the changes to the report (clarifying the 10 year cumulative nature of the data and the current harvest level being zero).

I will confirm the depth contour that was used, and report back here.

**Comment by tchaddad** [comment]
Unless ODFW can give us a smaller geographic description for the harvest area north of Coquille Point, we have no resolution for the first issue Dave is mentioning here.

**Comment by mmosesOCMP** [comment]
Removed.
