### ISSUE TITLE
State Parking Lot Trends (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#22]
-	Are the data cumulative counts for the time period, or average counts per year?
-	Harris Beach has a strange trend where the visitor count exceeds 1 million per year through 2009, then drops to 166,984 in 2010 and increases slowly from there.  I noticed a similar trend for South Beach state park, Oswald west and Fort Stevens.  I suspect there are others with the same trend.  Was there a change in how visitors were counted after 2009?  Some sites don’t show this trend.  Cape Lookout appears to have an opposite trend, suddenly increasing from 2009 to 2010.

**Comment by tchaddad** [comment]
We will try to confirm these details with OPRD, but my understanding is that these are counts per year, and not cumulative. 

Will also ask them about the trends Dave mentions to see if they have any insights...

**Comment by tchaddad** [comment]
@mmosesOCMP this layer came from Laurel Hillmann - can you pass Dave's questions on to her?

**Comment by mmosesOCMP** [comment]
Example here of steep drop in count after 2009:

![image](https://user-images.githubusercontent.com/62967932/79608935-adfc2500-80aa-11ea-9c97-0388b93bd466.png)

**Comment by mmosesOCMP** [comment]
Add to SeaSketch ticket and have removed until OPRD can clean up data.

**Comment by tchaddad** [comment]
Laurel provided a new data set for 2013-2019, so we will swap it out and provide it to the SeaSketch team

**Comment by tchaddad** [comment]
The new data is now posted to SeaSketch, please review and then close this issue.

**Comment by mmosesOCMP** [comment]
Data looks good but does not match Attendance at Nearby Parks query data in Human Use site report. I'm thinking we just need to make the same swap with the query data?
