### ISSUE TITLE
Land ownership (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#23]
The “water” polygons seem inconsistent among the estuaries.  In at least one case (Boone/Knute Slough area of Yaquina Bay), the polygon encompasses lands in private ownership.

**Comment by mmosesOCMP** [comment]
In looking at this one, I can see what he means by inconsistent between estuaries - compare Yaquina to Alsea Bays. But I'm not sure what to do about his concern about overlapping as that will be an issue of accuracy native to the dataset.
![image](https://user-images.githubusercontent.com/62967932/78933116-97781d00-7a5d-11ea-91b0-25ff19ed5d6f.png)

**Comment by tchaddad** [comment]
We should not even be showing the water polygons as they are clearly confusing, and frankly irrelevant to the layer. I will remove.

**Comment by tchaddad** [comment]
Having investigated this one, it is a layer from AGOL that we do not control, and it is largely duplicative of the Land Management data set, so my recommendation is that we remove this data set from the tool.

Assigning to Moses.

**Comment by mmosesOCMP** [comment]
Removed.
