### ISSUE TITLE
Scientific Intertidal Harvest of Invertebrates (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#24]
There are problems with depicting the collection data that are recorded within a broad spatial area (i.e., non-site-specific data).  Many of these areas are in the highest collection category, yet on a site-by-site basis they have much lower collection numbers than the site-specific data.  In fact, most of the sites in the broad spatial areas have zero collection.  The data don’t support spatial depiction of the broad areas.   The maps should either just depict collection areas supported with site specific data, or not include this layer at all.

**Comment by tchaddad** [comment]
Since we do not have the site specifics (ODFW did not provide), I would agree with removal. Assigning this to Moses as he has the power to do that...

**Comment by mmosesOCMP** [comment]
Removed
