### ISSUE TITLE
Aerial Imagery (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#25]
The aerial imagery layer appears to be low tide imagery north of approx. Cape Arago, but looks like high tide imagery south of that.  Am I imagining this?  Is it because the layer is based on the NAIP 2016 imagery?  This is not the primary imagery we used when developing the habitat maps.  The other imagery we used is much better and shows much more of the intertidal.

**Comment by tchaddad** [comment]
I will add the MLLW imagery that we used for the habitat mapping

**Comment by tchaddad** [comment]
I've added both the natural color and the color IR versions of the MLLW imagery.

Also added 2018 1 foot imagery, and NAIP imagery going back to 2005.

Closing this issue now.
