### ISSUE TITLE
Substrate types in Physical reports (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#28]
Physical Section: The substrate types data currently are subtidal data.  

The percent area of the substrate types isn’t calculating correctly in the table (total area 0.0%).

**Comment by tchaddad** [comment]
The SeaSketch team will have to fix the totals in the reports.

**Comment by mmosesOCMP** [comment]
![image](https://user-images.githubusercontent.com/62967932/81962082-1534c880-95c8-11ea-802a-b4e572fe05f7.png)

**Comment by tchaddad** [comment]
In our discussion today we guessed that the problem with the Area (%) field is the assumption that it is % of the site, while in face it seems likely that it is % of the Territorial Sea.

So at minimum, we need a label change on that column, to "Area (% TerSea)"

**Comment by danyocum** [comment]
Yes - it is the % of that substrate in the territorial sea. Do you want me to change it to be the % of the substrate within the sketch/collection?

**Comment by mmosesOCMP** [comment]
@danyocum Yes, please change it to % of the substrate within that particular sketch.

**Comment by danyocum** [comment]
@mmosesOCMP Ok, its updated to the % of the substrate within the sketch.

**Comment by DrewLanier** [comment]
looks good.
