### ISSUE TITLE
Polygon Description Pop-up Boxes

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#3]
Shape area and length have too many decimal places - should be limited to two decimal places. 

For shapes with long titles, the title spills over the maximize and close buttons on the top right of the description box. Either word wrap or truncating the shape names would resolve this.

**Comment by tchaddad** [comment]
This might be able to be controlled on the service end. Might need to ask Dan if this is correct.

**Comment by mmosesOCMP** [comment]
The SeaSketch team showed Andy how to do this on our admin side of things and Andy showed me. It's fairly simple and I will find time to knock it out. It will probably take less than an hour to complete.

**Comment by tchaddad** [comment]
Perfect!

**Comment by mmosesOCMP** [comment]
Completed this task as best I can tell, but check any new datalayers that we add and if they need adjusting.
