### ISSUE TITLE
Bird colony counts - Biological Reports (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#30]
Bird colony counts – Is the count column the total number of colonies in each category or the total number of birds?

**Comment by mmosesOCMP** [comment]
It is the number of colonies.

**Comment by tchaddad** [comment]
Maybe SeaSketch team can just alter the column name to reflect this improvement

**Comment by danyocum** [comment]
changed it to say 'number of colonies'
