### ISSUE TITLE
Fish Harvest Tables - Human Use Reports (DF)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#32]
These tables should not be in the report because:
i.	Problems with attributing data to long stretches of coastline (see comments above)
ii.	The counts imply that those numbers represent the harvest in the polygon you have drawn.  Even when the harvest count is attributed to a short section of coastline, the proposed designation polygon is likely to be a small subset of the harvest area, and it would be deceptive to imply all of the harvest occurs in the proposed area.

**Comment by tchaddad** [comment]
I can't disagree so would defer to Dave. Assigning to Moses as he has the power to remove the data from the tool. 

We may need SeaSketch to remove the report...

**Comment by mmosesOCMP** [comment]
@DrewLanier Thoughts on this one? And do you know if we would need the SeaSketch team to remove the report?

**Comment by tchaddad** [comment]
I don't think Andy is monitoring the issue list very closely, but I think @mmosesOCMP can make the call on removing this from the report.

I believe (despite the confusing issue name here) that these are the same data that are referred to in: https://github.com/orcoastalmgmt/orSeaSketch/issues/18

**Comment by danyocum** [comment]
These are the tables in the Human Use Tab in the Non Fish Harvest reports, correct?

**Comment by danyocum** [comment]
...and they're removed.
