### ISSUE TITLE
Add Black oystercatcher density layer (JL)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#33]
2015-17 Black oystercatcher abundance/bird density data previously provided by Portland Audubon (DLCD already has this information in the story map)

https://geo.maps.arcgis.com/apps/MapSeries/index.html?appid=1c84f165c0bf44c09026f548ad4c6578

**Comment by tchaddad** [comment]
These layers have now been added, please review, and close if things look good.

**Comment by tchaddad** [comment]
I think this is fine, so closing.
