### ISSUE TITLE
Add bio-blitz data (JL)

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#35]
Data gathered from intertidal-focused bio-blitzes via iNaturalist. Example:

https://www.inaturalist.org/projects/the-cape-perpetua-bioblitz-series

**Comment by tchaddad** [comment]
Moses, I've pulled and prepped the data from the above Cape Perpetua BioBlitz Series that you linked to. If there are others that I should pull from, please add those links below.

**Comment by tchaddad** [comment]
This data is highly geographically specific, so not sure how you want to handle it. 

There are 3,803 observations that are considered "research grade" in the collection, displayed below color coded by iconic taxon name.

![image](https://user-images.githubusercontent.com/1042618/79027521-607b3780-7b41-11ea-870e-79f41c8d5928.png)

![image](https://user-images.githubusercontent.com/1042618/79027606-bb149380-7b41-11ea-8a15-3d6ccf73c20f.png)

**Comment by mmosesOCMP** [comment]
@tchaddad I think that looks good, but I'm not sure I know enough about how it might be used to identify any potential issues with it. Can we still get this put into the tool?

**Comment by mmosesOCMP** [comment]
Closing because limited usefulness of data - area in image not eligible for designation, other areas not rocky habitats.
