### ISSUE TITLE
MR/MPA Data layer legend missing

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#4]
The legend for the Marine Reserves/Marine Protected Areas data layer is missing. It was there originally but disappeared at some point.

**Comment by tchaddad** [comment]
I think the source on this got swapped from our server to the AGOL server, and that is what killed the legend. Will try switching back...

**Comment by tchaddad** [comment]
Switching source did not make a difference, even though I can confirm that a legend is correctly generating on the source server. Maybe SeaSketch folks can take a quick look.

**Comment by tchaddad** [comment]
Resolved (?) as of May14th, 2020
