### ISSUE TITLE
Physical Report needs intertidal substrate calculation added

### ISSUE THREAD

**Issue by tchaddad** [orcoastalmgmt/orSeaSketch#43]
In #42 we are adding a new intertidal substrate layer.

Once incorporated, we will need the intertidal substrates to be broken out separately as an intertidal substrate report. 

We will keep the subtidal substrate report.

**Comment by tchaddad** [comment]
Almost done with the QAQC on this layer - will send to the SeaSketch team asap

**Comment by danyocum** [comment]
@tchaddad I've added the new report in the Substrate Types, the original is now titled 'Subtidal Substrates' and the new one is 'Intertidal Substrates'. The subtidal and intertidal overlap in spots, so you can have the two add up to more than 100%. I assume that's ok?

**Comment by tchaddad** [comment]
Yes thanks Dan that's ok and expected. thanks so much
