### ISSUE TITLE
US State Submerged Lands

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#5]
Data seems to be missing from this layer - nothing visualized on map.

**Comment by tchaddad** [comment]
The parent service is here:

https://coast.noaa.gov/arcgis/rest/services/MarineCadastre/USStateSubmergedLands/MapServer

And there appears to be an error at the source, so we will need to talk with the Marine Cadastre folks

**Comment by tchaddad** [comment]
This is resolved on the host server. Closing.
