### ISSUE TITLE
Offshore Wind Resource Potential

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#7]
No data apparent in this data layer - nothing visualized on the map.

**Comment by tchaddad** [comment]
The parent service is here:

https://coast.noaa.gov/arcgis/rest/services/MarineCadastre/OffshoreWindResourcePotential/MapServer

And there appears to be an error at the source, so we will need to talk with the Marine Cadastre folks

**Comment by tchaddad** [comment]
This has been resolved on the host server, so closing
