### ISSUE TITLE
Human --> Safety Data Layers Folder

### ISSUE THREAD

**Issue by mmosesOCMP** [orcoastalmgmt/orSeaSketch#8]
Many data layers in this folder are not loading/visualizing on the map, and none seem to have legend information. 

The layers of concern are:

~~Anchorage Areas~~
~~Danger Zones and Restricted Areas~~
~~Formerly Used Defense Sites (Unexploded Ordnance)~~
~~Transit Counts - All Vessels (2016)~~
~~Wrecks and Obstructions~~

**Comment by tchaddad** [comment]
Same problem as the other Marine Cadastre layers, source is here:

https://coast.noaa.gov/arcgis/rest/services/MarineCadastre/NavigationAndMarineTransportation/MapServer

**Comment by tchaddad** [comment]
NOTE: This issue should really be broken out into one issue for each of the component problem layers.

**Comment by tchaddad** [comment]
Replaced "Transit Counts - All Vessels (2016)" with a folder of counts from 2017 broken out by vessel type.

**Comment by tchaddad** [comment]
Fixed Anchorage Areas

**Comment by tchaddad** [comment]
Fixed Danger Zones and Restricted Areas

**Comment by tchaddad** [comment]
Fixed Wrecks and Obstructions

**Comment by tchaddad** [comment]
Fixed Formerly Used Defense Sites

**Comment by tchaddad** [comment]
I think this covers all the items for this ticket, so closing...
